<?php
session_start(); require 'config/db.php'; require 'includes/functions.php'; require 'config/paypal.php'; ensure_portal_schema($pdo); ensure_warehouse_schema($pdo);
if(empty($_SESSION['client'])) redirect('client_login.php');
$client=$_SESSION['client']; if(!isset($_SESSION['cart'])) $_SESSION['cart']=[]; $err='';
try{ $pdo->query("CREATE TABLE IF NOT EXISTS CheckoutDetails (checkout_id INT AUTO_INCREMENT PRIMARY KEY, porosi_id INT NOT NULL, emri VARCHAR(150), email VARCHAR(150), telefoni VARCHAR(50), adresa VARCHAR(255), qyteti VARCHAR(100), shenim TEXT, data_krijimit DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"); }catch(Exception $e){}
if(isset($_GET['remove'])){ unset($_SESSION['cart'][(int)$_GET['remove']]); redirect('client_cart.php'); }
if(isset($_GET['clear'])){ $_SESSION['cart']=[]; redirect('client_cart.php'); }
$items=[]; $total=0;
if($_SESSION['cart']){ $ids=array_keys($_SESSION['cart']); $in=str_repeat('?,',count($ids)-1).'?'; $st=$pdo->prepare("SELECT produkt_id, emri, cmimi, sasia_ne_stok FROM Produktet WHERE produkt_id IN ($in)"); $st->execute($ids); foreach($st->fetchAll() as $p){ $qty=min((int)$_SESSION['cart'][$p['produkt_id']], (int)$p['sasia_ne_stok']); if($qty<=0) continue; $p['qty']=$qty; $p['line']=$qty*(float)$p['cmimi']; $total+=$p['line']; $items[]=$p; }}
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='checkout'){
  if(!$items) $err='Shporta është bosh.'; else {
    $name=trim($_POST['emri']??''); $email=trim($_POST['email']??''); $phone=trim($_POST['telefoni']??''); $address=trim($_POST['adresa']??''); $city=trim($_POST['qyteti']??''); $note=trim($_POST['shenim']??'');
    if($name==='' || !valid_email($email) || $phone==='' || $address==='' || $city==='') $err='Plotëso emër, email të vlefshëm, telefon, adresë dhe qytet.';
    else { $pdo->beginTransaction(); $ins=$pdo->prepare("INSERT INTO Porosite (klient_id,statusi,totali) VALUES (?,'Në pritje pagese',?)"); $ins->execute([$client['klient_id'],$total]); $order=$pdo->lastInsertId(); $det=$pdo->prepare('INSERT INTO DetajetPorosise (porosi_id,produkt_id,sasia,cmimi) VALUES (?,?,?,?)'); foreach($items as $p){ $det->execute([$order,$p['produkt_id'],$p['qty'],$p['cmimi']]); } $pdo->prepare('INSERT INTO CheckoutDetails(porosi_id,emri,email,telefoni,adresa,qyteti,shenim) VALUES(?,?,?,?,?,?,?)')->execute([$order,$name,$email,$phone,$address,$city,$note]); $pdo->commit(); $_SESSION['cart']=[]; redirect('paypal_checkout.php?order_id='.$order); }
  }
}
$portalRole='client'; $portalUser=$client; $pageTitle='Shporta'; include 'includes/portal_header.php'; ?>
<?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>
<section class="page-title-card"><div><span class="eyebrow">Checkout</span><h1>Shporta</h1></div><a class="btn secondary" href="client_shop.php">Vazhdo blerjen</a></section>
<div class="saas-layout"><section class="card"><div class="section-head"><h2>Produktet në shportë</h2><a class="btn secondary small" href="client_cart.php?clear=1">Pastro shportën</a></div><div class="table-wrap"><table><tr><th>Produkt</th><th>Sasia</th><th>Çmimi</th><th>Totali</th><th></th></tr><?php foreach($items as $p):?><tr><td><b><?=e($p['emri'])?></b></td><td><?=e($p['qty'])?></td><td><?=money($p['cmimi'])?></td><td><?=money($p['line'])?></td><td><a class="btn danger small" href="client_cart.php?remove=<?=$p['produkt_id']?>">Hiq</a></td></tr><?php endforeach;?><?php if(!$items):?><tr><td colspan="5" class="empty-state">Shporta është bosh.</td></tr><?php endif;?></table></div><div class="cart-total"><span>Total</span><b><?=money($total)?></b></div></section><section class="card"><h2>Konfirmo porosinë</h2><form method="post" class="form-grid"><input type="hidden" name="action" value="checkout"><div class="span-all"><label>Emër/Mbiemër</label><input class="input" name="emri" value="<?=e($client['emri']??'')?>" required></div><div><label>Email</label><input class="input" type="email" name="email" value="<?=e($client['email']??'')?>" required></div><div><label>Telefon</label><input class="input" name="telefoni" value="<?=e($client['telefoni']??'')?>" required></div><div class="span-all"><label>Adresa</label><input class="input" name="adresa" value="<?=e($client['adresa']??'')?>" required></div><div><label>Qyteti</label><input class="input" name="qyteti" value="<?=e($client['qyteti']??'')?>" required></div><div class="span-all"><label>Shënim</label><textarea class="input" name="shenim"></textarea></div><div class="span-all"><button class="btn primary" <?=$items?'':'disabled'?>>Krijo porosi dhe vazhdo pagesën</button></div></form></section></div>
<?php include 'includes/portal_footer.php'; ?>
