<?php

session_start(); require 'config/db.php'; require 'includes/functions.php'; require_login(); ensure_portal_schema($pdo); ensure_warehouse_schema($pdo);
$title='Produktet'; $subtitle=''; $action=$_GET['action']??'list';
if($_SERVER['REQUEST_METHOD']==='POST'){
    $data=[$_POST['kategoria_id']?:null,$_POST['furnizues_id']?:null,$_POST['magazine_id']?:1,$_POST['barkodi'],$_POST['emri'],$_POST['pershkrimi'],$_POST['njesia'],$_POST['cmimi'],$_POST['sasia_ne_stok'],$_POST['stok_minimal'],$_POST['stok_maksimal']];
    if(!empty($_POST['produkt_id'])){ $data[]=(int)$_POST['produkt_id']; $pdo->prepare('UPDATE Produktet SET kategoria_id=?,furnizues_id=?,magazine_id=?,barkodi=?,emri=?,pershkrimi=?,njesia=?,cmimi=?,sasia_ne_stok=?,stok_minimal=?,stok_maksimal=? WHERE produkt_id=?')->execute($data); }
    else $pdo->prepare('INSERT INTO Produktet(kategoria_id,furnizues_id,magazine_id,barkodi,emri,pershkrimi,njesia,cmimi,sasia_ne_stok,stok_minimal,stok_maksimal) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute($data);
    redirect('products.php');
}
$cats=$pdo->query('SELECT * FROM Kategorite ORDER BY emri')->fetchAll(); $sups=$pdo->query('SELECT * FROM Furnizuesit ORDER BY emri')->fetchAll(); $whs=$pdo->query('SELECT * FROM Magazinat ORDER BY emri')->fetchAll();
include 'includes/header.php';
if($action==='create'||$action==='edit'):
$row=['produkt_id'=>'','kategoria_id'=>'','furnizues_id'=>'','magazine_id'=>'1','barkodi'=>'','emri'=>'','pershkrimi'=>'','njesia'=>'cope','cmimi'=>'','sasia_ne_stok'=>'0','stok_minimal'=>'5','stok_maksimal'=>'100'];
if($action==='edit'){ $st=$pdo->prepare('SELECT * FROM Produktet WHERE produkt_id=?'); $st->execute([(int)$_GET['id']]); $row=$st->fetch(); }
?>
<div class="card"><h2><?=$action==='edit'?'Ndrysho produkt':'Shto produkt të ri'?></h2><form method="post" class="form-grid"><input type="hidden" name="produkt_id" value="<?=e($row['produkt_id'])?>"><div><label>Emri</label><input class="input" name="emri" required value="<?=e($row['emri'])?>"></div><div><label>Barkodi</label><input class="input" name="barkodi" value="<?=e($row['barkodi'])?>"></div><div><label>Kategoria</label><select name="kategoria_id"><?php foreach($cats as $c): ?><option value="<?=$c['kategoria_id']?>" <?=$row['kategoria_id']==$c['kategoria_id']?'selected':''?>><?=e($c['emri'])?></option><?php endforeach; ?></select></div><div><label>Furnizuesi</label><select name="furnizues_id"><?php foreach($sups as $s): ?><option value="<?=$s['furnizues_id']?>" <?=$row['furnizues_id']==$s['furnizues_id']?'selected':''?>><?=e($s['emri'])?></option><?php endforeach; ?></select></div><div><label>Magazina</label><select name="magazine_id"><?php foreach($whs as $w): ?><option value="<?=$w['magazine_id']?>" <?=$row['magazine_id']==$w['magazine_id']?'selected':''?>><?=e($w['emri'])?></option><?php endforeach; ?></select></div><div><label>Çmimi</label><input class="input" type="number" step="0.01" name="cmimi" required value="<?=e($row['cmimi'])?>"></div><div><label>Njësia</label><input class="input" name="njesia" value="<?=e($row['njesia'])?>"></div><div><label>Sasia në stok</label><input class="input" type="number" name="sasia_ne_stok" value="<?=e($row['sasia_ne_stok'])?>"></div><div><label>Stok minimal</label><input class="input" type="number" name="stok_minimal" value="<?=e($row['stok_minimal'])?>"></div><div><label>Stok maksimal</label><input class="input" type="number" name="stok_maksimal" value="<?=e($row['stok_maksimal'])?>"></div><div class="full"><label>Përshkrimi</label><textarea name="pershkrimi" class="input"><?=e($row['pershkrimi'])?></textarea></div><div class="full"><button class="btn primary">Ruaj</button> <a class="btn gray" href="products.php">Anulo</a></div></form></div>
<?php else: 
$q=trim($_GET['q']??''); $cat=trim($_GET['cat']??'');
$sql='SELECT p.*,k.emri kategori,f.emri furnizues,m.emri magazine FROM Produktet p LEFT JOIN Magazinat m ON m.magazine_id=p.magazine_id LEFT JOIN Kategorite k ON k.kategoria_id=p.kategoria_id LEFT JOIN Furnizuesit f ON f.furnizues_id=p.furnizues_id WHERE 1=1'; $params=[];
if($q){$sql.=' AND (p.emri LIKE ? OR p.barkodi LIKE ? OR k.emri LIKE ?)'; $params=["%$q%","%$q%","%$q%"]; }
if($cat){$sql.=' AND p.kategoria_id=?'; $params[]=$cat; }
$sql.=' ORDER BY p.produkt_id DESC LIMIT 120'; $st=$pdo->prepare($sql); $st->execute($params); $rows=$st->fetchAll(); ?>
<div class="card products-polish"><div class="modern-product-header"><div><span class="eyebrow">Inventari</span><h2>Menaxhimi i produkteve</h2><p>Lista e produkteve me stok, çmim dhe veprime të shpejta.</p></div><a class="btn add-product-btn" href="products.php?action=create">+ Shto produkt</a></div><div class="toolbar"><form class="filters" method="get"><input class="input" id="liveProductSearch" name="q" placeholder="Kërko live produkt, barkod, furnizues..." value="<?=e($q)?>"><select name="cat" onchange="this.form.submit()"><option value="">Të gjitha kategoritë</option><?php foreach($cats as $c): ?><option value="<?=$c['kategoria_id']?>" <?=$cat==$c['kategoria_id']?'selected':''?>><?=e($c['emri'])?></option><?php endforeach; ?></select><button class="btn gray">Filtro</button><a class="btn gray" href="products.php">Pastro</a></form></div><div class="table-wrap"><table><tr><th>Barkodi</th><th>Produkti</th><th>Kategoria</th><th>Furnizuesi</th><th>Magazina</th><th>Çmimi</th><th>Stok</th><th>Status</th><th>Veprime</th></tr><?php foreach($rows as $r): $status=$r['sasia_ne_stok'] <= $r['stok_minimal']?'low':($r['sasia_ne_stok'] >= $r['stok_maksimal']?'warn':'ok'); $searchText=strtolower(($r['emri']??'').' '.($r['barkodi']??'').' '.($r['kategori']??'').' '.($r['furnizues']??'').' '.($r['magazine']??'')); ?><tr class="product-row" data-search="<?=e($searchText)?>"><td><?=e($r['barkodi'])?></td><td><b><?=e($r['emri'])?></b></td><td><?=e($r['kategori'])?></td><td><?=e($r['furnizues'])?></td><td><?=e($r['magazine'])?></td><td><?=money($r['cmimi'])?></td><td><?=e($r['sasia_ne_stok'])?></td><td><span class="badge <?=$status?>"><?=$status==='low'?'I ulët':($status==='warn'?'I lartë':'OK')?></span></td><td class="actions"><a class="btn gray" href="stock.php?product=<?=$r['produkt_id']?>">Stok</a><a class="btn gray" href="products.php?action=edit&id=<?=$r['produkt_id']?>">Edit</a><a class="btn danger" data-confirm="Ta fshij këtë produkt?" href="products.php?delete=<?=$r['produkt_id']?>">Fshi</a></td></tr><?php endforeach; ?></table><div id="noLiveResults" class="empty-state" style="display:none">Nuk u gjet asnjë produkt me këtë kërkim.</div></div></div>
<?php endif; include 'includes/footer.php'; ?>
